import type { Metadata } from "next";
import "./globals.css";
import VerticalLineLeft from "@/components/verticalLineLeft";
import VerticalLineRight from "@/components/verticalLineRight";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<html lang="en">
<head>
<link rel="stylesheet" href="https://use.typekit.net/ach3hzm.css" />
</head>
<body
className="h-[100dvh] pb-[env(safe-area-inset-bottom)]"
style={{ fontFamily: '"courier-std", monospace' }}
>
<div>
<VerticalLineLeft />
<VerticalLineRight />
{children}
</div>
</body>
</html>
  );
}