import type { Metadata } from "next";
import { Noto_Sans_Mono } from 'next/font/google';
import "./globals.css";
import VerticalLineLeft from "@/components/verticalLineLeft";
import VerticalLineRight from "@/components/verticalLineRight";

const mono = Noto_Sans_Mono({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<html lang="en" className={mono.className}>
  <body className="pb-[env(safe-area-inset-bottom)]">
    <div className="">
        <VerticalLineLeft />
        <VerticalLineRight />
          {children}
    </div>
  </body>
</html>

  );
}
